FROM node:22-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 4200
# ng serve bindeado a 0.0.0.0 para que Docker lo exponga
CMD ["npx", "ng", "serve", "--host", "0.0.0.0", "--poll", "2000"]