server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: poshibrido-backend
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/pos_hibrido}
    username: ${SPRING_DATASOURCE_USERNAME:pos_user}
    password: ${SPRING_DATASOURCE_PASSWORD:pos_secret_password}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true
    locations: classpath:db/platform
    default-schema: platform
    create-schemas: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
